config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html




  
  
  get 'posts/:post_id/likes' => 'likes#create'
  get 'posts/:post_id/likes/:id' => 'likes#destroy'
  
  resources :users, only: [:show]
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  root 'posts#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    #tweetsテーブルから中間テーブルに対する関連付け
  has_many :post_tag_relations, dependent: :destroy
  #tweetsテーブルから中間テーブルを介してTagsテーブルへの関連付け
  has_many :tags, through: :post_tag_relations, dependent: :destroy
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :name, presence: true
  #Tagsテーブルから中間テーブルに対する関連付け
  has_many :post_tag_relations, dependent: :destroy
  #Tagsテーブルから中間テーブルを介してArticleテーブルへの関連付け
  has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  has_many :posts, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])


  end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
    
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    
    def index
        @posts = Post.all

        if params[:tag_ids]
          @posts = []
          params[:tag_ids].each do |key, value|
            if value == "1"
              tag_posts = Tag.find_by(name: key).posts
              @posts = @posts.empty? ? tag_posts : @posts & tag_posts
            end
          end
        end

        if params[:tag]
          Tag.create(name: params[:tag])
        end
    end
    #追加箇所
    def new
        @post = Post.new
    end
    
    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end
      
    def show
        @post = Post.find(params[:id])
    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
    end

    def post_params
      params.require(:post).permit(:body,:lat,:lng)
     end

    private
    def post_params
        params.require(:post).permit(:name)
    end
     #ここまで
    
     def post_params
        params.require(:post).permit(:name, tag_ids: [])
      end
     

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
<%= link_to "ログイン", post_index_path %>
<%= link_to "新規登録", new_user_registration_path %>

app/views/hello/link.html.erb
My name is Runners.
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Runners</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3bc7b9efd2.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <header>
  <h1>Runners</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>

 <div class="push"></div>
 <footer>
 <p>Copyright © GeekSalon All Rights Reserved.</p>
 
 </footer>

</body>
 


</html>

app/views/maps/index.html.erb
<%= form_with(model: @post, local: true) do |f| %>
  <div class="actions">
    <%= f.label :body,"内容" %>
    <%= f.text_field :body %>
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>
    <%= f.submit %>
  </div>
<% end %>

<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDE-4NuoUSKb0XUYiPwIeBVMu_UQ8Bydsg&callback=initMap" async defer></script>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/posts/index.html.erb


<h2>一覧ページ</h2>
<h4>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
</h4>
<p><%= link_to "新規投稿へ", new_post_path %></p>
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <% Tag.all.each do |t| %>
      <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
  <% end %>
  <p><%= submit_tag '検索' %></p>
<% end %>

<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <p>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
  </p>
<% end %>

<div class="posts-container">
  <% @posts.each do |t| %>
    <div class="post">
    <div class="main-box">
      <%= link_to t.user.name, user_path(t.user.id) %>
      <%= t.user.email %>
      <div class="left-container"><%= t.name %></div>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(t) %>
          <%= button_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>  
          <% end %>
        <% else %>
          <%= button_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>  
          <% end %>
        <% end %>
      <% else %>
        <i class="far fa-heart"></i><%= t.likes.count %>
      <% end %>
      <div class="right-container">
        <h8><%= link_to "詳細へ", post_path(t.id) %></h8>
        <% if user_signed_in? && current_user.id == t.user_id %>
        <h8><%= link_to "編集する", edit_post_path(t.id) %></h8>
        <h8><%= button_to "削除する", post_path(t.id), method: :delete %></h8>
      </div>
      <p class="time"><%= t.created_at %></p>
    </div>
    </div>
  <% end %>
  <% end %>
</div>


<h2>Map</h2>
<div class="first">
<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
</div>
<!-- 下の1行を追加 -->
<div id="display">場所を調べよう！</div>

<div id='map'></div>

<div class="second">
<style>
#map {
  height: 400px;
  width: 50%;
  margin-right: auto;
  margin-left: auto;

}
</style>
</div>

<script>
let map
let geocoder
// 下の1行を追加 
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      // 下の1行を追加 
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDE-4NuoUSKb0XUYiPwIeBVMu_UQ8Bydsg&callback=initMap" async defer></script>








app/views/posts/new.html.erb
<h2>新規投稿ページ</h2>
<h4><%= link_to "一覧に戻る", posts_path %></h4>
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
  </div>
    
  <p><%= f.submit "投稿する" %></p>
<% end %>





<h2>Map</h2>
<div class="first">
<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
</div>

<div id="display">場所を調べよう！</div>

<div id='map'></div>

<div class="second">
<style>
#map {
  height: 600px;
  width: 50%;
  margin-right: auto;
  margin-left: auto;
}
</style>
</div>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDE-4NuoUSKb0XUYiPwIeBVMu_UQ8Bydsg&callback=initMap" async defer></script>








app/views/posts/show.html.erb

<h2>Post詳細</h2>
<h4><%= link_to "Post一覧に戻る", posts_path %></h4>
<div class="posts-container">
<div class="post">
  <p><%= @post.name %></p>

 
  <p><%= @post.created_at %></p>
  <% @post.tags.each do |tag| %>
    <span><%= tag.name %></span>
  <% end %>
   <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
        <%= link_to post_like_path(@post), method: :delete do %>
          <i class="fas fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% else %>
        <%= link_to post_likes_path(@post), method: :post do %>
          <i class="far fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <i class="far fa-heart"></i><%= @post.likes.count %>
      #<p>いいねの数 = </p><%= @post.likes.count %>
    <% end %>
    
  <%= link_to "編集する", edit_post_path(@post.id) %>

</div>
</div>

<h2>Map</h2>
<div class="first">
<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
</div>
<!-- 下の1行を追加 -->
<div id="display">場所を調べよう！</div>

<div id='map'></div>

<div class="second">
<style>
#map {
  height: 400px;
  width: 50%;
  margin-right: auto;
  margin-left: auto;
}
</style>
</div>

<script>
let map
let geocoder
// 下の1行を追加 
const display = document.getElementById('display')

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 40.7828, lng:-73.9653},
    zoom: 12,
  });

  marker = new google.maps.Marker({
    position:  {lat: 40.7828, lng:-73.9653},
    map: map
  });
}

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
      // 下の1行を追加 
      display.textContent = "検索結果：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDE-4NuoUSKb0XUYiPwIeBVMu_UQ8Bydsg&callback=initMap" async defer></script>



<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>



app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h2>マイページ</h2>
<h5>
<%= link_to "Post一覧に戻る", posts_path %>
</h5>
<h5>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>
</h5>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>



<h6>ユーザーの投稿一覧</h6>
<div class="myposts">
<% @user.posts.each do |t| %>
  <div class="mypost">
  <%= t.user.name %>
  <%= t.name %>
  </div>
<% end %>
</div>



<!-- 以下はいいね機能を実装している場合-->
<h6>ユーザーがいいねした投稿一覧</h6>
<% @user.liked_posts.each do |t| %>
  <div class="likedpost">
  <%= t.user.name %>
  <%= t.name %>
  </div>
<% end %>
<!-- ここまで-->
